FROM jupyter/datascience-notebook:latest

# install additional package...
RUN pip install --no-cache-dir psycopg2-binary \
	python-pachyderm pystardog \
	pandas_profiling pyodbc \
	azure-storage-file-datalake azure-storage-blob \
	azure-storage-file-share

